### ISSUE TITLE
where is null ga support ya bang ? 

### ISSUE THREAD

**Issue by ciskhalifa** [fauzan1892/CodeIgniter_Datatables_serverside#1]
$where = array('aktivasi_app' => 0, 'aktivasi_app' => " IS NULL");
echo $this->Data_model->get_tables_where($tables, $search, $where);

**Comment by fauzan1892** [comment]
sudah ku update bang @ciskhalifa, silahkan testing

**Comment by ciskhalifa** [comment]
terima kasih bang
